import './globals.css'
import { Inter } from 'next/font/google'
import { NaviBar } from './components/Navibar'
import { Box } from './components/Box'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <html lang="en">
      <body className={inter.className}>  
      <Box
    css={{
      maxW: "100%"
    }}
  > <NaviBar/>
      {children}   </Box></body>
   
    </html>
  )
}
